### ISSUE TITLE
Location names and attribution missing in twitter browser

### ISSUE THREAD

**Issue by customlogic** [ofZach/landlines#3]
On iOS, when opening the link within the Twitter app, the location name and attribution is missing

**Comment by customlogic** [comment]
![img_5224](https://cloud.githubusercontent.com/assets/1166244/21251631/15fdeb56-c304-11e6-905e-21331ba54545.PNG)

**Comment by ofZach** [comment]
can confirm that it appears that the page is cut off -- on the landing page you can drag to the bottom -- it may be we are getting the wrong viewport size or need to change our resize function?

![img_3914](https://cloud.githubusercontent.com/assets/142897/21258388/bed43334-c34a-11e6-9c41-d107b79ca293.PNG)
![img_3913](https://cloud.githubusercontent.com/assets/142897/21258390/c1372d20-c34a-11e6-82a8-b99ed07e6efc.PNG)

potentially relevant: 

http://stackoverflow.com/questions/27379581/web-page-not-getting-100-height-in-twitter-app-on-ios-8
https://nicolas-hoizey.com/2015/02/viewport-height-is-taller-than-the-visible-part-of-the-document-in-some-mobile-browsers.html
http://stackoverflow.com/questions/35421247/wrong-viewport-page-height-in-embedded-facebook-browser-in-ios-9-x
https://www.scirra.com/forum/games-are-stuck-partially-offscreen-when-opened-from-twitter_t168226

**Comment by ofZach** [comment]
I think I have fixed this but invite some testing across devices and browsers to make sure this fix doesn't have impact elsewhere...  

you can send the appspot link to yourself via direct message if it's helpful to test on twitter / ios: 

![photo on 12-19-16 at 9 35 am](https://cloud.githubusercontent.com/assets/142897/21316403/89fce030-c5ce-11e6-89ea-0696ef1b1526.jpg)

**Comment by ofZach** [comment]
ps: if it's helpful the fix is here: https://github.com/ofZach/landlines/commit/c57982126c6918d73383ff6dc95d8e8335dba402   I'm not 100% sure if both are needed...

**Comment by ofZach** [comment]
ok this fix is in and pushed, closing...
